### ISSUE TITLE
Undefined array index in Cart::remove()

### ISSUE THREAD

**Issue by mlocati** [concretecms-community-store/community_store#804]
I have this error in my logs:

```
Undefined array key 0

URL: https://mywebsite/cart/remove

File: [webroot]/packages/community_store/src/CommunityStore/Cart/Cart.php
Line: 603

Trace:
#0 [webroot]/packages/community_store/src/CommunityStore/Cart/Cart.php(603): Whoops\Run->handleError()
#1 [webroot]/packages/community_store/controllers/single_page/cart.php(226): Concrete\Package\CommunityStore\Src\CommunityStore\Cart\Cart::remove()
#2 [internal function]: Concrete\Package\CommunityStore\Controller\SinglePage\Cart->remove()
```

PS: I'm far away from my PC these days, I can't submit a pull request.

**Comment by Mesuva** [comment]
I reckon this may have been caused by a double click of a remove button.
I've put a quick check in the function involved
